"""
`tomte scaffold` — generate canonical project files from tomte templates.

Today this ships:

  * ``tomte scaffold tox`` — render ``tox.ini`` from
    ``tomte/templates/tox.ini.template`` using overrides declared in the
    target repo's ``pyproject.toml`` under ``[tool.tomte.scaffold]``.

**Scope.** Two template variants ship today, selected via
``[tool.tomte.scaffold] template_kind``:

  * ``"agent"`` (default) — the homogeneous AEA agent fleet that ships
    ``packages/valory/`` skills + agents + services and bootstraps via
    the ``autonomy`` CLI: mech, mech-predict, mech-agents-fun,
    mech-server, IEKit, optimus, meme-ooorr, trader, market-creator,
    mech-interact.
  * ``"library"`` — repos that don't ship ``packages/`` and don't need
    the autonomy bootstrap; lint envs target a single source tree
    instead of ``SERVICE_SPECIFIC_PACKAGES``. Currently: mech-client.

Framework repos (``open-aea``, ``open-autonomy``) keep their own
hand-written ``tox.ini`` — they're the source of truth that tomte's
canonical configs are derived from, so scaffolding them would invert
the dependency direction. They still consume ``tomte/configs/*``
resources (``from tomte.configs import PYLINTRC, MYPY_INI, …``) via
``--rcfile=`` / ``--config=`` flags in their own tox envs.

The substitution model is intentionally low-tech:
``string.Template``-style ``$VAR`` placeholders, no Jinja, no logic in
the template. Anything more dynamic than "stamp this string in" belongs
in the per-repo `pyproject.toml [tool.tomte.scaffold]` block, not in
the template.

Per-repo overrides live in ``[tool.tomte.scaffold]``::

    [tool.tomte.scaffold]
    open_autonomy_version = "0.21.19"
    open_aea_version = "2.2.1"
    packages_paths = "packages/valory"
    skills_paths = "packages/valory/skills"
    known_first_party = "autonomy"
    service_public_id = "valory/mech"

    # Multi-line lists rendered into the file as-is. Indent two spaces
    # for tox-section continuation.
    service_specific_packages = '''
      packages/valory/contracts/olas_mech
      packages/valory/skills/mech_abci
      packages/valory/skills/task_execution
    '''
    pytest_targets = "packages/valory/skills/mech_abci/tests"

    extra_deps_packages = '''
        web3<8,>=7.0.0
        openai==1.30.2
    '''

    extra_testenvs = '''
    [testenv:my-custom-env]
    commands = ...
    '''

    upstream_pins = '''
        --upstream valory-xyz/open-autonomy@0.21.19
        --upstream valory-xyz/open-aea@2.2.1
    '''

    check_handlers_ignores = "-i abstract_abci -i contract_subscription"

    # Per-repo pylint extensions. Tomte's canonical pylintrc carries
    # only pylint-internal codes (no downstream library names), so each
    # repo declares its own ignored-modules + extra disables here. The
    # scaffolder renders each into a complete CLI flag on the pylint
    # testenv command, or an empty string if omitted.
    extra_pylint_ignored_modules = "web3,pandas,numpy,anthropic"
    extra_pylint_disables = "C0111,R0902"

The CLI refuses to overwrite an existing ``tox.ini`` whose first line is
not the canonical "; tox.ini — generated by `tomte scaffold tox`"
marker, unless ``--force`` is supplied. That preserves any hand-written
``tox.ini`` that pre-dates the scaffold (e.g. on initial migration).
"""

from __future__ import annotations

import sys
from pathlib import Path
from string import Template
from typing import Any, Dict

import click

try:
    import tomllib  # type: ignore[import-not-found]  # py311+
except ImportError:  # pragma: no cover
    import tomli as tomllib  # type: ignore[no-redef]

from tomte import __version__


GENERATED_MARKER = "; tox.ini — generated by `tomte scaffold tox`"


# Per-template required keys + defaults. Anything without a default must
# be present in `[tool.tomte.scaffold]` or the scaffolder errors out —
# better than silently emitting a tox.ini with a literal `$VAR`.
_AGENT_REQUIRED_KEYS = (
    "open_autonomy_version",
    "open_aea_version",
    "packages_paths",
    "service_specific_packages",
    "pytest_targets",
    "service_public_id",
    "known_first_party",
)

_AGENT_DEFAULTS: Dict[str, str] = {
    "tomte_version": __version__,
    "skills_paths": "",  # filled from packages_paths if absent
    "extra_deps_packages": "",
    "extra_testenvs": "",
    "upstream_pins": "        --upstream valory-xyz/open-autonomy@0.21.19",
    "check_handlers_ignores": "",
    # User-facing pylint extension keys. Collapsed by _render_pylint_flags
    # into a single `extra_pylint_flags` substitution that the template
    # interpolates. Empty by default → no flags rendered.
    "extra_pylint_ignored_modules": "",
    "extra_pylint_disables": "",
}

_LIBRARY_REQUIRED_KEYS = (
    "lint_targets",
    "known_first_party",
)

_LIBRARY_DEFAULTS: Dict[str, str] = {
    "tomte_version": __version__,
    "extra_deps": "",
    "extra_testenvs": "",
    "extra_pylint_ignored_modules": "",
    "extra_pylint_disables": "",
}

_TEMPLATE_KINDS = ("agent", "library")
_TEMPLATE_FILES = {
    "agent": "tox.ini.template",
    "library": "tox.ini.library.template",
}
_REQUIRED_KEYS_BY_KIND = {
    "agent": _AGENT_REQUIRED_KEYS,
    "library": _LIBRARY_REQUIRED_KEYS,
}
_DEFAULTS_BY_KIND = {
    "agent": _AGENT_DEFAULTS,
    "library": _LIBRARY_DEFAULTS,
}


def _load_pyproject(pyproject_path: Path) -> Dict[str, Any]:
    if not pyproject_path.is_file():
        raise click.UsageError(f"No pyproject.toml at {pyproject_path}.")
    with pyproject_path.open("rb") as handle:
        return tomllib.load(handle)


def _gather_substitutions(
    scaffold_block: Dict[str, Any], template_kind: str
) -> Dict[str, str]:
    """Build the substitution dict for the chosen template, validate required keys."""
    out: Dict[str, str] = dict(_DEFAULTS_BY_KIND[template_kind])
    for key, value in scaffold_block.items():
        if key == "template_kind":
            continue  # selector, not a substitution variable
        if not isinstance(value, str):
            raise click.UsageError(
                f"[tool.tomte.scaffold].{key} must be a string "
                f"(got {type(value).__name__})."
            )
        out[key] = value

    missing = [k for k in _REQUIRED_KEYS_BY_KIND[template_kind] if not out.get(k)]
    if missing:
        raise click.UsageError(
            f"[tool.tomte.scaffold] (template_kind={template_kind!r}) is "
            "missing required keys: " + ", ".join(missing)
        )

    if template_kind == "agent" and not out["skills_paths"]:
        out["skills_paths"] = f"{out['packages_paths']}/skills"

    _render_pylint_flags(out)

    out_upper = {k.upper(): v for k, v in out.items()}
    return out_upper


def _render_pylint_flags(out: Dict[str, str]) -> None:
    """Collapse user-facing pylint extras into a single `extra_pylint_flags` (in place).

    Users declare two keys in `[tool.tomte.scaffold]`:
    `extra_pylint_ignored_modules = "web3,pandas"` and
    `extra_pylint_disables = "C0111,R0902"`. The template interpolates
    a single `$EXTRA_PYLINT_FLAGS` substitution holding both as fully
    formed CLI flags joined by spaces, or the empty string if neither
    is set — that way the rendered tox.ini doesn't carry a dangling
    line-continuation backslash when nothing is declared.
    """
    flags = []
    raw_modules = out.pop("extra_pylint_ignored_modules", "").strip()
    if raw_modules:
        flags.append(f"--ignored-modules={raw_modules}")
    raw_disables = out.pop("extra_pylint_disables", "").strip()
    if raw_disables:
        flags.append(f"--disable={raw_disables}")
    out["extra_pylint_flags"] = " ".join(flags)


def _render(template_text: str, substitutions: Dict[str, str]) -> str:
    template = Template(template_text)
    try:
        return template.substitute(substitutions)
    except KeyError as exc:
        raise click.UsageError(
            f"Template references unknown variable {exc.args[0]!r}. "
            "Add it to [tool.tomte.scaffold] or update the template."
        ) from exc


def _looks_generated(target: Path) -> bool:
    if not target.is_file():
        return True
    first_line = target.read_text(encoding="utf-8").splitlines()[:1]
    return bool(first_line and first_line[0].strip() == GENERATED_MARKER)


@click.group(name="scaffold")
def scaffold() -> None:
    """Generate canonical project files from tomte-shipped templates."""


@scaffold.command(name="tox")
@click.option(
    "--repo-root",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=Path.cwd(),
    help="Repo to scaffold (default: CWD).",
)
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help="Overwrite an existing tox.ini even if it looks hand-written.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Print the rendered tox.ini to stdout instead of writing.",
)
def scaffold_tox(repo_root: Path, force: bool, dry_run: bool) -> None:
    """Render tox.ini from the canonical template + pyproject overrides."""
    repo_root = repo_root.resolve()
    pyproject = _load_pyproject(repo_root / "pyproject.toml")
    scaffold_block = (
        pyproject.get("tool", {}).get("tomte", {}).get("scaffold", {})
    )
    if not scaffold_block:
        raise click.UsageError(
            "No [tool.tomte.scaffold] block in pyproject.toml. "
            "See `tomte scaffold tox --help` for the expected schema."
        )

    template_kind = scaffold_block.get("template_kind", "agent")
    if template_kind not in _TEMPLATE_KINDS:
        raise click.UsageError(
            f"[tool.tomte.scaffold].template_kind must be one of "
            f"{_TEMPLATE_KINDS}; got {template_kind!r}."
        )

    substitutions = _gather_substitutions(scaffold_block, template_kind)

    template_path = (
        Path(__file__).parent / "templates" / _TEMPLATE_FILES[template_kind]
    )
    rendered = _render(
        template_path.read_text(encoding="utf-8"), substitutions
    )

    target = repo_root / "tox.ini"
    if dry_run:
        click.echo(rendered)
        return

    if not force and not _looks_generated(target):
        raise click.UsageError(
            f"{target} exists and does not look like a previously-generated "
            "scaffold (first line is not the canonical marker). "
            "Re-run with --force to overwrite, or remove it first."
        )

    target.write_text(rendered, encoding="utf-8")
    click.echo(f"Wrote {target} ({len(rendered.splitlines())} lines).")


if __name__ == "__main__":
    scaffold()
