"""`tomte scaffold tox` — render tox.ini from canonical template + per-repo `[tomte-scaffold]`.

Per-repo settings live in a `[tomte-scaffold]` section at the top of
the consuming repo's `tox.ini`. The scaffolder reads that section,
renders the canonical template into the rest of the file, and writes
the merged result back. The `[tomte-scaffold]` section survives every
re-generation.

Two template variants:

  * ``agent`` — `packages/valory/` skills + agents + services, autonomy
    bootstrap. Mech, mech-predict, mech-agents-fun, mech-server, IEKit,
    optimus, meme-ooorr, trader, market-creator, mech-interact.
  * ``library`` — single source tree, no autonomy bootstrap. Currently
    mech-client.

Framework repos (open-aea, open-autonomy) keep hand-written tox.ini.
They consume `tomte/configs/*` directly via `--rcfile=` / `--config=`
flags, but don't run the scaffold.
"""

from __future__ import annotations

import configparser
import sys
from pathlib import Path
from string import Template
from typing import Any, Dict

import click

from tomte import __version__


GENERATED_MARKER = "; tox.ini — generated by `tomte scaffold tox`"


# Per-template required keys + defaults. Missing-without-default → error.
_AGENT_REQUIRED_KEYS = (
    "open_autonomy_version",
    "open_aea_version",
    "packages_paths",
    "service_specific_packages",
    "pytest_targets",
    "service_public_id",
    "known_first_party",
)

_AGENT_DEFAULTS: Dict[str, str] = {
    "tomte_version": __version__,
    "tomte_dep_pin": f"=={__version__}",  # PyPI pin; override to "@ git+https://…@<sha>" pre-publish.
    "skills_paths": "",  # filled from packages_paths if absent
    "extra_deps_packages": "",
    "extra_testenvs": "",
    "extra_mypy_overrides": "",
    "upstream_pins": "--upstream valory-xyz/open-autonomy@0.21.19",
    "check_handlers_ignores": "",
    "extra_pylint_ignored_modules": "",
    "extra_pylint_disables": "",
}

_LIBRARY_REQUIRED_KEYS = (
    "lint_targets",
    "known_first_party",
)

_LIBRARY_DEFAULTS: Dict[str, str] = {
    "tomte_version": __version__,
    "tomte_dep_pin": f"=={__version__}",
    "extra_deps": "",
    "extra_testenvs": "",
    "extra_mypy_overrides": "",
    "extra_pylint_ignored_modules": "",
    "extra_pylint_disables": "",
}

_TEMPLATE_KINDS = ("agent", "library")
_TEMPLATE_FILES = {
    "agent": "tox.ini.template",
    "library": "tox.ini.library.template",
}
_REQUIRED_KEYS_BY_KIND = {
    "agent": _AGENT_REQUIRED_KEYS,
    "library": _LIBRARY_REQUIRED_KEYS,
}
_DEFAULTS_BY_KIND = {
    "agent": _AGENT_DEFAULTS,
    "library": _LIBRARY_DEFAULTS,
}


_SCAFFOLD_SECTION = "tomte-scaffold"


def _load_scaffold_block(tox_ini_path: Path) -> Dict[str, str]:
    if not tox_ini_path.is_file():
        raise click.UsageError(
            f"No tox.ini at {tox_ini_path}. To bootstrap a new repo, create a "
            "stub tox.ini containing only a `[tomte-scaffold]` section, then "
            "re-run `tomte scaffold tox`."
        )
    parser = configparser.ConfigParser()
    parser.read(tox_ini_path, encoding="utf-8")
    if not parser.has_section(_SCAFFOLD_SECTION):
        raise click.UsageError(
            f"No [{_SCAFFOLD_SECTION}] section in {tox_ini_path}. "
            "See `tomte scaffold tox --help` for the schema."
        )
    return dict(parser.items(_SCAFFOLD_SECTION))


def _emit_scaffold_section(scaffold_block: Dict[str, str]) -> str:
    """Re-emit the `[tomte-scaffold]` section verbatim at the top of the rendered tox.ini."""
    lines = [f"[{_SCAFFOLD_SECTION}]"]
    for key, value in scaffold_block.items():
        if "\n" in value:
            lines.append(f"{key} =")
            for chunk in value.splitlines():
                lines.append(f"    {chunk}")
        else:
            lines.append(f"{key} = {value}")
    lines.append("")
    return "\n".join(lines)


# Multi-line continuation values need re-indenting after configparser strip.
# upstream_pins is rendered inline now (single line in template) so no indent.
_INDENT_BY_KEY = {
    "extra_deps_packages": 4,   # tox `deps =` continuation depth
    "extra_deps": 4,
}


def _reindent_continuation(value: str, indent: int) -> str:
    stripped = value.strip("\n")
    if not stripped:
        return ""
    prefix = " " * indent
    return "\n".join(
        (prefix + line) if line.strip() else line
        for line in stripped.splitlines()
    )


def _gather_substitutions(
    scaffold_block: Dict[str, str], template_kind: str
) -> Dict[str, str]:
    """Build the substitution dict for the chosen template, validate required keys."""
    out: Dict[str, str] = dict(_DEFAULTS_BY_KIND[template_kind])
    for key, value in scaffold_block.items():
        if key == "template_kind":
            continue  # selector, not a substitution variable
        out[key] = value

    missing = [k for k in _REQUIRED_KEYS_BY_KIND[template_kind] if not out.get(k)]
    if missing:
        raise click.UsageError(
            f"[{_SCAFFOLD_SECTION}] (template_kind={template_kind!r}) is "
            "missing required keys: " + ", ".join(missing)
        )

    if template_kind == "agent" and not out["skills_paths"]:
        out["skills_paths"] = f"{out['packages_paths']}/skills"

    for key, indent in _INDENT_BY_KEY.items():
        if key in out and "\n" in out[key].strip():
            out[key] = _reindent_continuation(out[key], indent)

    _render_pylint_flags(out)

    out_upper = {k.upper(): v for k, v in out.items()}
    return out_upper


def _render_pylint_flags(out: Dict[str, str]) -> None:
    """Collapse user-facing pylint extras into a single `extra_pylint_flags` (in place).

    Users declare two keys in `[tool.tomte.scaffold]`:
    `extra_pylint_ignored_modules = "web3,pandas"` and
    `extra_pylint_disables = "C0111,R0902"`. The template interpolates
    a single `$EXTRA_PYLINT_FLAGS` substitution holding both as fully
    formed CLI flags joined by spaces, or the empty string if neither
    is set — that way the rendered tox.ini doesn't carry a dangling
    line-continuation backslash when nothing is declared.
    """
    flags = []
    raw_modules = out.pop("extra_pylint_ignored_modules", "").strip()
    if raw_modules:
        flags.append(f"--ignored-modules={raw_modules}")
    raw_disables = out.pop("extra_pylint_disables", "").strip()
    if raw_disables:
        flags.append(f"--disable={raw_disables}")
    out["extra_pylint_flags"] = " ".join(flags)


def _render(template_text: str, substitutions: Dict[str, str]) -> str:
    template = Template(template_text)
    try:
        return template.substitute(substitutions)
    except KeyError as exc:
        raise click.UsageError(
            f"Template references unknown variable {exc.args[0]!r}. "
            "Add it to [tool.tomte.scaffold] or update the template."
        ) from exc


def _looks_generated(target: Path) -> bool:
    if not target.is_file():
        return True
    first_line = target.read_text(encoding="utf-8").splitlines()[:1]
    return bool(first_line and first_line[0].strip() == GENERATED_MARKER)


@click.group(name="scaffold")
def scaffold() -> None:
    """Generate canonical project files from tomte-shipped templates."""


@scaffold.command(name="tox")
@click.option(
    "--repo-root",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=Path.cwd(),
    help="Repo to scaffold (default: CWD).",
)
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help="Overwrite an existing tox.ini even if it looks hand-written.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Print the rendered tox.ini to stdout instead of writing.",
)
def scaffold_tox(repo_root: Path, force: bool, dry_run: bool) -> None:
    """Render tox.ini from canonical template + repo's [tomte-scaffold] section."""
    repo_root = repo_root.resolve()
    target = repo_root / "tox.ini"
    scaffold_block = _load_scaffold_block(target)

    template_kind = scaffold_block.get("template_kind", "agent")
    if template_kind not in _TEMPLATE_KINDS:
        raise click.UsageError(
            f"[{_SCAFFOLD_SECTION}].template_kind must be one of "
            f"{_TEMPLATE_KINDS}; got {template_kind!r}."
        )

    substitutions = _gather_substitutions(scaffold_block, template_kind)

    template_path = (
        Path(__file__).parent / "templates" / _TEMPLATE_FILES[template_kind]
    )
    rendered_template = _render(
        template_path.read_text(encoding="utf-8"), substitutions
    )
    # Strip the template's leading marker line — we re-emit it before the
    # [tomte-scaffold] block so the marker stays on line 1.
    body = "\n".join(
        line
        for line in rendered_template.splitlines()
        if line.strip() != GENERATED_MARKER
    )
    rendered = (
        GENERATED_MARKER + "\n\n"
        + _emit_scaffold_section(scaffold_block) + "\n"
        + body
    )
    if not rendered.endswith("\n"):
        rendered += "\n"

    if dry_run:
        click.echo(rendered)
        return

    if not force and not _looks_generated(target):
        raise click.UsageError(
            f"{target} exists and does not look like a previously-generated "
            "scaffold (first line is not the canonical marker). "
            "Re-run with --force to overwrite, or remove it first."
        )

    target.write_text(rendered, encoding="utf-8")
    click.echo(f"Wrote {target} ({len(rendered.splitlines())} lines).")


if __name__ == "__main__":
    scaffold()
